[package]
name = "g2048engine"
version = "0.1.0"
authors = ["Elias Eskelinen <elias.eskelinen@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.4.10", features = ["tls"] }
rocket_cors = "0.5.1"
rocket_contrib = "0.4.10"
read_input = "0.8.6"
twothousand-forty-eight = { path = "./twothousand-forty-eight" }
serde = { version = "1.0.130", features = ["derive"] }