[package]
name = "OispaHallaAnticheat"
version = "0.2.0"
authors = ["Elias Eskelinen <elias.eskelinen@pm.me>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twothousand-forty-eight = { path = "./twothousand-forty-eight" }
# Server
rocket = { version = "0.4.10", features = ["tls"], optional = true }
rocket_cors = { version = "0.5.1", optional = true }
rocket_contrib = { version = "0.4.10", optional = true }
serde = { version = "1.0.130", features = ["derive"], optional = true }
# Game
read_input = { version = "0.8.6", optional = true }

[features]
default = ["server", "bot", "game"]
server = ["rocket", "rocket_cors", "rocket_contrib", "serde"]
bot = ["read_input"]
game = ["read_input"]

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = 'unwind'
incremental = false
codegen-units = 16
rpath = false